name: RST to Markdown Conversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run the job every Monday at midnight

jobs:
  convert-rst-to-md:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Own Repository
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Clone External Repository
      run: |
        git clone -b 14.0 https://github.com/odoo/documentation cloned_repo

    - name: Set up Pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Convert RST files to Markdown
      run: |
        input_directory='cloned_repo/content'
        output_directory='content'

        # Create the output directory if it does not exist
        mkdir -p "$output_directory"

        find "$input_directory" -name '*.rst' | while read file; do
            # Get the parent directory path of the .rst file
            dir_path=$(dirname "${file}")
            
            # Remove the input directory prefix to obtain the subdirectory structure
            sub_dir="${dir_path#$input_directory}"
            
            # Create the same subdirectory in the output directory
            mkdir -p "$output_directory$sub_dir"
            
            # Extract the base name of the file for the output file name
            base_name=$(basename "${file%.rst}")
            
            # Set the output file name with the same subdirectory as the input file
            output_file="$output_directory$sub_dir/${base_name}.md"
            
            # Convert the .rst file to .md
            pandoc --from=rst --to=gfm --output="$output_file" "$file" || true
            
            echo "Converted: $file -> $output_file"
        done

        echo "Conversion completed!"

    - name: Configure Git Author Info
      run: |
        git config --local user.email "lucas.joliveau@kapreon.com"
        git config --local user.name "Lucas Joliveau"

    - name: Commit and Push Markdown Files
      run: |
        # Add the converted files to the current repository
        git add content
        # Commit only if there are changes
        git commit -m "Convert RST files to Markdown and push to repository" || echo "No changes to commit"
        # Push to the current branch of the current repository
        git push origin 'main'